unrailedtrain.map_generator.register_biome({
  name = "grassland",
  node_top = "default:dirt_with_grass",
  node_stone = "default:stone",
  depth_top = 1,
  node_filler =  "default:dirt",
  depth_filler = 1,
  node_riverbed = "default:sand",
  depth_riverbed = 2,
  y_max = upper_limit,
  y_min = 6,
  dec={
    {chance=0.5,schematic=minetest.get_modpath("default").."/schematics/apple_tree.mts", offset_x=-3,offset_z=-3,offset_y=-1},
    {chance=0.05,schematic=minetest.get_modpath("default").."/schematics/bush.mts", offset_x=-1,offset_z=-1},
    {chance=5, node="default:grass_1"},
    {chance=5, node="default:grass_2"},
    {chance=5, node="default:grass_3"},
    {chance=5, node="default:grass_4"},
    {chance=5, node="default:grass_5"},
    {chance=0.25, node="flowers:rose"},
    {chance=0.25, node="flowers:tulip"},
    {chance=0.25, node="flowers:dandelion_yellow"},
    {chance=0.25, node="flowers:chrysanthemum_green"},
    {chance=0.25, node="flowers:geranium"},
    {chance=0.25, node="flowers:viola"},
    {chance=0.25, node="flowers:dandelion_white"},
    {chance=0.25, node="flowers:tulip_black"},
    {chance=0.05, node="flowers:mushroom_brown"},
    {chance=0.05, node="flowers:mushroom_red"},
    }
})